version: '3.8'

services:
  # PostgreSQL Database Service
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres       # Database username
      POSTGRES_PASSWORD: password  # Database password
      POSTGRES_DB: wild     # Database name
    ports:
      - "5432:5432"               # Expose PostgreSQL on port 5432
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data

  # Spring Boot Application Service
  app:
    image: mnr
    container_name: spring_boot_app
    depends_on:
      - db                       # Wait for the database to be ready
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wild
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8080"              # Expose Spring Boot on port 8080

# Volume for PostgreSQL data persistence
volumes:
  db_data:
