spring:
  application:
    name: mnr
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://db:5432/wild
    url: jdbc:postgresql://dpg-csfrkblds78s7390i840-a.oregon-postgres.render.com:5432/wild_p7mm
    username: nurkan
    password: ei72X63L9b0q8hccoYzJHD6V2Grq0CaW
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        ddl-auto: validate
        default_schema: public
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  mustache:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      cache: false

server:
  port: 10000
#logging:
#  level:
#    org.springframework: DEBUG
#  file:

#    name: app.log